/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

rootProject.name = "npvrus"
include("app")

  gradle.rootProject {
      task checkSpecv1 {
          group = 'Verification'
          description = 'Custom task to perform Specv1 checks.'

          doLast {
              println 'Executing checkSpecv1 task...'
              // Add your task-specific logic here
          }
      }
  }
